// Generated by scripts/generate-communications-contract.mjs. Do not edit.
import { z } from "zod";

export const idSchema = z.guid();

export const actorSchema = z.strictObject({
  "accountRef": z.string().min(1).max(128),
});

export const entitySchema = z.strictObject({
  "type": z.enum(["mention","hashtag","cashtag","bot_command","url","email","phone_number","bold","italic","underline","strikethrough","spoiler","code","pre","text_link","blockquote","expandable_blockquote"]),
  "offset": z.number().int().min(0).max(2147483647),
  "length": z.number().int().min(1),
  "url": z.url().max(2048).regex(new RegExp("^https://")).optional(),
  "language": z.string().max(64).optional(),
});

export const buttonSchema = z.strictObject({
  "text": z.string().min(1).max(64),
  "url": z.url().max(2048).regex(new RegExp("^https://")),
});

export const contentSchema = z.union([z.strictObject({
  "type": z.literal("text"),
  "text": z.string().min(1).max(4096),
  "entities": z.array(entitySchema).min(0).max(100),
  "buttons": z.array(buttonSchema).min(0).max(20),
}),
z.strictObject({
  "type": z.literal("photo"),
  "text": z.string().max(1024),
  "entities": z.array(entitySchema).min(0).max(100),
  "buttons": z.array(buttonSchema).min(0).max(20),
  "fileId": z.string().regex(new RegExp("^[A-Za-z0-9_-]{1,1024}$")),
}),
z.strictObject({
  "type": z.literal("video"),
  "text": z.string().max(1024),
  "entities": z.array(entitySchema).min(0).max(100),
  "buttons": z.array(buttonSchema).min(0).max(20),
  "fileId": z.string().regex(new RegExp("^[A-Za-z0-9_-]{1,1024}$")),
}),
z.strictObject({
  "type": z.literal("video_note"),
  "text": z.string().max(0),
  "entities": z.array(entitySchema).min(0).max(0),
  "buttons": z.array(buttonSchema).min(0).max(20),
  "fileId": z.string().regex(new RegExp("^[A-Za-z0-9_-]{1,1024}$")),
}),
z.strictObject({
  "type": z.literal("voice"),
  "text": z.string().max(1024),
  "entities": z.array(entitySchema).min(0).max(100),
  "buttons": z.array(buttonSchema).min(0).max(20),
  "fileId": z.string().regex(new RegExp("^[A-Za-z0-9_-]{1,1024}$")),
}),
z.strictObject({
  "type": z.literal("document"),
  "text": z.string().max(1024),
  "entities": z.array(entitySchema).min(0).max(100),
  "buttons": z.array(buttonSchema).min(0).max(20),
  "fileId": z.string().regex(new RegExp("^[A-Za-z0-9_-]{1,1024}$")),
})]);

export const partSchema = z.strictObject({
  "partId": z.guid(),
  "content": contentSchema,
});

export const stepSchema = z.strictObject({
  "stepId": z.guid(),
  "delaySeconds": z.number().int().min(0).max(2147483647),
  "parts": z.array(partSchema).min(1).max(20),
});

export const sourceSchema = z.strictObject({
  "sourceId": z.guid(),
  "code": z.string().regex(new RegExp("^m_[A-Za-z0-9_-]{1,48}$")),
  "name": z.string().min(1).max(128),
});

export const audienceSchema = z.union([
z.strictObject({
  "kind": z.literal("all"),
}),
z.strictObject({
  "kind": z.literal("funnels"),
  "funnelIds": z.array(z.guid()).min(1).max(100),
})
]);

export const targetSchema = z.strictObject({
  "kind": z.enum(["material","series"]),
  "targetId": z.guid(),
});

export const templateSchema = z.strictObject({
  "templateId": z.guid(),
  "revision": z.number().int().min(0).max(2147483647),
  "botIdentity": z.string().min(1).max(128),
  "content": contentSchema,
});

export const entryResponseSchema = z.strictObject({
  "stepId": z.guid(),
  "parts": z.array(partSchema).min(1).max(100),
});

export const trackingActorSchema = z.strictObject({
  "serviceRef": z.literal("platform-tracking"),
});

export const requestSchema = z.union([
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("templates.read"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "templateId": z.guid(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("templates.save"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "templateId": z.guid(),
  "content": contentSchema,
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("funnels.read"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "funnelId": z.guid(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("funnels.list"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "cursor": z.string().min(1).max(128).optional(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("funnels.save"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "funnelId": z.guid(),
  "name": z.string().min(1).max(128),
  "steps": z.array(stepSchema).min(0).max(100),
  "sources": z.array(sourceSchema).min(0).max(100),
  "isDefault": z.boolean(),
  "entryResponse": entryResponseSchema,
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("funnels.publish"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "funnelId": z.guid(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("funnels.preview"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "funnelId": z.guid(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("funnels.lifecycle"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "funnelId": z.guid(),
  "action": z.enum(["pause","resume","archive","restore"]),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("funnels.rollback"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "funnelId": z.guid(),
  "publishedRevision": z.number().int().min(0).max(2147483647),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("broadcasts.read"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "broadcastId": z.guid(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("broadcasts.save"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "broadcastId": z.guid(),
  "parts": z.array(partSchema).min(1).max(20),
  "audience": audienceSchema,
  "scheduledAt": z.union([z.iso.datetime({ offset: true }), z.null()]),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("broadcasts.launch"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "broadcastId": z.guid(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("broadcasts.lifecycle"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "broadcastId": z.guid(),
  "action": z.enum(["pause","resume","cancel"]),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("delivery.resolve"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "deliveryId": z.guid(),
  "partId": z.guid(),
  "action": z.enum(["skip","retry"]),
  "duplicateRiskAccepted": z.boolean(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("templates.testSend"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "templateId": z.guid(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("eligibility.check"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "targets": z.array(targetSchema).min(1).max(100),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("tracking.resolve"),
  "operationId": z.guid(),
  "actor": trackingActorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "token": z.string().regex(new RegExp("^[A-Za-z0-9_-]{32,128}$")),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("tracking.recordHit"),
  "operationId": z.guid(),
  "actor": trackingActorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "eventId": z.guid(),
  "token": z.string().regex(new RegExp("^[A-Za-z0-9_-]{32,128}$")),
  "occurredAt": z.iso.datetime({ offset: true }),
  "traffic": z.enum(["unknown","known_automation"]),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("statistics.read"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "funnelId": z.guid().optional(),
  "broadcastId": z.guid().optional(),
  "cursor": z.string().min(1).max(128).optional(),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("intro.read"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({

}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("intro.save"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "introId": z.guid(),
  "parts": z.array(partSchema).min(1).max(100),
}),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "operation": z.literal("deliveries.read"),
  "operationId": z.guid(),
  "actor": actorSchema,
  "expectedRevision": z.number().int().min(0).max(2147483647),
  "payload": z.strictObject({
  "deliveryId": z.guid().optional(),
  "funnelId": z.guid().optional(),
  "broadcastId": z.guid().optional(),
  "cursor": z.string().max(128).optional(),
}),
})
]);

export const authorizationRequestSchema = z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "requestId": z.guid(),
  "permission": z.literal("communications:manage"),
  "subject": z.union([
z.strictObject({
  "kind": z.literal("account"),
  "accountRef": z.string().min(1).max(128),
}),
z.strictObject({
  "kind": z.literal("telegram"),
  "accountRef": z.string().min(1).max(128),
  "telegramIdentityRef": z.string().min(1).max(128),
  "botIdentity": z.string().min(1).max(128),
})
]),
});

export const authorizationResponseSchema = z.union([
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "requestId": z.guid(),
  "status": z.literal("allowed"),
  "accountRef": z.string().min(1).max(128),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "requestId": z.guid(),
  "status": z.literal("denied"),
})
]);

export const errorSchema = z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.enum(["unauthorized","forbidden","not_found","malformed","unsupported_content","revision_conflict","operation_conflict","authorization_unavailable","not_implemented"]),
});

export const templateResponseSchema = z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "template": templateSchema,
});

export const funnelSchema = z.strictObject({
  "funnelId": z.guid(),
  "revision": z.number().int().min(0).max(2147483647),
  "publishedRevision": z.union([z.number().int().min(1), z.null()]),
  "lifecycle": z.enum(["draft","published","paused","archived"]),
  "name": z.string().min(1).max(128),
  "steps": z.array(stepSchema).min(0).max(100),
  "sources": z.array(sourceSchema).min(0).max(100),
  "isDefault": z.boolean(),
  "entryResponse": entryResponseSchema,
});

export const publishPreviewSchema = z.strictObject({
  "funnelId": z.guid(),
  "revision": z.number().int().min(0).max(2147483647),
  "addedStepIds": z.array(z.guid()).min(0).max(100),
  "editedStepIds": z.array(z.guid()).min(0).max(100),
  "deletedStepIds": z.array(z.guid()).min(0).max(100),
  "reorderedStepIds": z.array(z.guid()).min(0).max(100),
  "eligibleContacts": z.number().int().min(0).max(2147483647),
  "completedParticipantsReceivingNewSteps": z.number().int().min(0).max(2147483647),
  "validationErrors": z.array(z.strictObject({
  "target": targetSchema,
  "reason": z.enum(["not_found","not_published","not_free","incomplete"]),
})).min(0).max(100),
});

export const broadcastSchema = z.strictObject({
  "broadcastId": z.guid(),
  "revision": z.number().int().min(0).max(2147483647),
  "state": z.enum(["draft","scheduled","running","paused","cancelled","completed"]),
  "parts": z.array(partSchema).min(1).max(20),
  "audience": audienceSchema,
  "scheduledAt": z.union([z.iso.datetime({ offset: true }), z.null()]),
  "audienceSnapshotId": z.union([z.guid(), z.null()]),
  "snapshotSize": z.number().int().min(0).max(2147483647),
});

export const countsSchema = z.strictObject({
  "sent": z.number().int().min(0).max(2147483647),
  "suppressed": z.number().int().min(0).max(2147483647),
  "failed": z.number().int().min(0).max(2147483647),
  "unknown": z.number().int().min(0).max(2147483647),
  "partialCancelled": z.number().int().min(0).max(2147483647),
  "pending": z.number().int().min(0).max(2147483647),
});

export const statisticsSchema = z.strictObject({
  "totalBotContacts": z.number().int().min(0).max(2147483647),
  "reachable": z.number().int().min(0).max(2147483647),
  "blocked": z.number().int().min(0).max(2147483647),
  "marketingOff": z.number().int().min(0).max(2147483647),
  "uniqueParticipants": z.number().int().min(0).max(2147483647),
  "deliveries": countsSchema,
  "trackingHits": z.number().int().min(0).max(2147483647),
  "uniqueTokensWithHits": z.number().int().min(0).max(2147483647),
  "analyticsLagSeconds": z.number().int().min(0).max(2147483647),
  "contacts": z.array(z.strictObject({
  "contactId": z.guid(),
  "firstSourceId": z.union([z.guid(), z.null()]),
  "latestSourceId": z.union([z.guid(), z.null()]),
  "entries": z.array(z.strictObject({
  "sourceId": z.guid(),
  "enteredAt": z.iso.datetime({ offset: true }),
})).min(0).max(100),
})).min(0).max(100),
  "nextCursor": z.union([z.string().max(128), z.null()]),
});

export const introSchema = z.strictObject({
  "introId": z.guid(),
  "revision": z.number().int().min(0),
  "parts": z.array(partSchema).min(1).max(100),
});

export const deliveryPartSchema = z.strictObject({
  "partId": z.guid(),
  "state": z.enum(["pending","in_flight","sent","failed","unknown","suppressed","skipped","cancelled"]),
  "diagnosticCode": z.union([z.string().max(128), z.null()]),
  "attempts": z.array(z.strictObject({
  "attemptId": z.guid(),
  "attemptedAt": z.iso.datetime({ offset: true }),
  "outcome": z.enum(["sent","api_rejected","retryable","unknown"]),
  "diagnosticCode": z.union([z.string().max(128), z.null()]),
  "duplicateRiskAccepted": z.boolean(),
})).max(100),
});

export const deliverySchema = z.strictObject({
  "deliveryId": z.guid(),
  "revision": z.number().int().min(0),
  "contactId": z.guid(),
  "funnelId": z.union([z.guid(), z.null()]),
  "broadcastId": z.union([z.guid(), z.null()]),
  "stepId": z.union([z.guid(), z.null()]),
  "publishedRevision": z.number().int().min(0),
  "snapshot": z.array(partSchema).min(1).max(100),
  "parts": z.array(deliveryPartSchema).max(100),
  "cancelRequested": z.boolean(),
  "completedAt": z.union([z.iso.datetime({ offset: true }), z.null()]),
});

export const responseSchema = z.union([
errorSchema,
templateResponseSchema,
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "funnel": funnelSchema,
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "funnels": z.array(funnelSchema).min(0).max(100),
  "nextCursor": z.union([z.string().max(128), z.null()]),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "preview": publishPreviewSchema,
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "broadcast": broadcastSchema,
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "deliveryId": z.guid(),
  "partId": z.guid(),
  "outcome": z.enum(["skipped","retry_requested"]),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "testDeliveryId": z.guid(),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "targets": z.array(z.strictObject({
  "target": targetSchema,
  "eligible": z.boolean(),
  "safeUrl": z.union([z.string().max(2048), z.null()]),
  "reason": z.enum(["eligible","not_found","not_published","not_free","incomplete"]),
})).min(0).max(100),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "safeUrl": z.url().max(2048).regex(new RegExp("^https://")),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "eventId": z.guid(),
  "outcome": z.enum(["recorded","duplicate"]),
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "statistics": statisticsSchema,
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "intro": introSchema,
}),
z.strictObject({
  "contractVersion": z.literal("inside-communications-v1"),
  "status": z.literal("ok"),
  "deliveries": z.array(deliverySchema).max(100),
  "nextCursor": z.union([z.string().max(128), z.null()]),
})
]);
