#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13
PROOF_DRY_RUN="${CREDENTIALED_PROOF_DRY_RUN:-0}"
RECOVERY_INPUT_FILE=".credentialed-proof/recovery-input.env"
umask 077

preflight() {
  local cli repository_root expected_pnpm
  for cli in git node pnpm; do
    if ! command -v "$cli" >/dev/null 2>&1; then
      warn "required CLI is unavailable: $cli"
      exit 1
    fi
  done
  if [[ "$(node -p 'process.versions.node.split(".")[0]')" != "24" ]]; then
    warn "Node 24 from .node-version is required"
    exit 1
  fi
  repository_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  if [[ "$repository_root" != "$PWD" || ! -f scripts/credentialed-proof-wizard.sh ]]; then
    warn "run this wizard from the inside-telegram repository root"
    exit 1
  fi
  expected_pnpm="$(node -p 'require("./package.json").packageManager.split("@")[1]')"
  if [[ "$(pnpm --version)" != "$expected_pnpm" ]]; then
    warn "pnpm $expected_pnpm from package.json is required"
    exit 1
  fi
  export ENV_FILE
  export ENV_FILE_OVERRIDE=true
  if [[ "$PROOF_DRY_RUN" == "1" ]]; then
    return
  fi
  case "$ENV_FILE" in
    /*|../*|*/../*)
      warn "ENV_FILE must be a repository-relative ignored path"
      exit 1
      ;;
  esac
  if ! git check-ignore -q -- "$ENV_FILE" || ! git check-ignore -q -- .credentialed-proof/evidence.json; then
    warn "ENV_FILE and .credentialed-proof evidence must both be ignored by git"
    exit 1
  fi
  touch "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  pnpm credentialed-proof:preflight "$ENV_FILE"
}

remove_recovery_input() {
  rm -f -- "$RECOVERY_INPUT_FILE"
}

write_recovery_input() {
  mkdir -p .credentialed-proof
  remove_recovery_input
  : > "$RECOVERY_INPUT_FILE"
  {
    printf '%s=%s\n' \
      RECOVERY_REF "$RECOVERY_REF" \
      OPERATOR_REF "$OPERATOR_REF" \
      REASON_REF "$REASON_REF" \
      TELEGRAM_IDENTITY_REF "$TELEGRAM_IDENTITY_REF" \
      SOURCE_ACCOUNT_REF "$SOURCE_ACCOUNT_REF" \
      TARGET_ACCOUNT_REF "$TARGET_ACCOUNT_REF" \
      TARGET_LINK_TRANSACTION_REF "$TARGET_LINK_TRANSACTION_REF"
    if [[ -n "${CONFIRMED_SOURCE_ACCOUNT_REF:-}" ]]; then
      printf '%s=%s\n' CONFIRMED_SOURCE_ACCOUNT_REF "$CONFIRMED_SOURCE_ACCOUNT_REF"
    fi
    if [[ -n "${CONFIRMED_TARGET_ACCOUNT_REF:-}" ]]; then
      printf '%s=%s\n' CONFIRMED_TARGET_ACCOUNT_REF "$CONFIRMED_TARGET_ACCOUNT_REF"
    fi
  } > "$RECOVERY_INPUT_FILE"
  chmod 600 "$RECOVERY_INPUT_FILE"
}

trap remove_recovery_input EXIT
trap 'remove_recovery_input; exit 129' HUP
trap 'remove_recovery_input; exit 130' INT
trap 'remove_recovery_input; exit 143' TERM

probe() {
  if [[ "$PROOF_DRY_RUN" == "1" ]]; then
    note "dry-run: skipped credentialed probe $*"
  else
    pnpm credentialed-proof:probe "$@"
  fi
}

scrub_proof_environment() {
  write_env TELEGRAM_BOT_TOKEN revoked
  write_env TELEGRAM_PROOF_BOT_ID disposed
  write_env TELEGRAM_PROOF_BOT_USERNAME disposed
  write_env TELEGRAM_WEBHOOK_SECRET disposed
  write_env TELEGRAM_CANONICAL_CHAT_ID disposed
  write_env TELEGRAM_PROOF_WEBHOOK_URL disposed
  write_env TELEGRAM_PROOF_RETRY_MARKER disposed
  write_env PLATFORM_INTEGRATION_SECRET disposed
  write_env PLATFORM_EVIDENCE_DELIVERY_URL disposed
  write_env PLATFORM_EVIDENCE_DELIVERY_SECRET disposed
  write_env PLATFORM_EVIDENCE_DELIVERY_MODE disabled
  write_env TELEGRAM_DELIVERY_MODE disabled
  write_env TELEGRAM_MEMBERSHIP_MODE disabled
  write_env WORKERS_ENABLED false
  write_env TELEGRAM_PROOF_DISPOSAL_STATE complete
  unset TELEGRAM_BOT_TOKEN TELEGRAM_PROOF_BOT_ID TELEGRAM_PROOF_BOT_USERNAME
  unset TELEGRAM_WEBHOOK_SECRET TELEGRAM_CANONICAL_CHAT_ID TELEGRAM_PROOF_WEBHOOK_URL
  unset TELEGRAM_PROOF_RETRY_MARKER PLATFORM_INTEGRATION_SECRET
  unset PLATFORM_EVIDENCE_DELIVERY_URL PLATFORM_EVIDENCE_DELIVERY_SECRET
}

complete_credential_disposal() {
  local state="$1"
  if [[ -z "$state" ]]; then
    if ! confirm "Delete pending test updates, revoke the bot token, and dispose the temporary chat now?"; then
      warn "proof cannot complete until every ephemeral credential and resource is disposed"
      exit 1
    fi
    state="webhook-removal-pending"
    write_env TELEGRAM_PROOF_DISPOSAL_STATE "$state"
  fi
  if [[ "$state" == "webhook-removal-pending" ]]; then
    probe remove-webhook
    state="token-rotation-pending"
    write_env TELEGRAM_PROOF_DISPOSAL_STATE "$state"
  fi
  if [[ "$state" == "token-rotation-pending" ]]; then
    open_url "https://t.me/BotFather"
    step "If the old token is still valid, send /token, select this dedicated proof bot, and generate a replacement. If BotFather already issued the replacement, do not rotate again."
    pause "Press Enter after the old token is revoked"
    probe verify-revoked
    state="external-resources-pending"
    write_env TELEGRAM_PROOF_DISPOSAL_STATE "$state"
  fi
  if [[ "$state" == "external-resources-pending" ]]; then
    step "Delete or leave the temporary closed group according to the recorded disposition; remove the temporary HTTPS endpoint and Platform credentials."
    pause "Press Enter after the chat, endpoint, and matching Platform secrets are disposed"
    write_env TELEGRAM_PROOF_TEMPORARY_RESOURCES_DISPOSED true
    probe record-resource-disposal
    state="local-scrub-pending"
    write_env TELEGRAM_PROOF_DISPOSAL_STATE "$state"
  fi
  if [[ "$state" == "local-scrub-pending" ]]; then
    scrub_proof_environment
    state="complete"
  fi
  if [[ "$state" != "complete" ]]; then
    warn "unknown TELEGRAM_PROOF_DISPOSAL_STATE; inspect the protected ENV_FILE"
    exit 1
  fi
  step "Give the final redacted evidence file to the reviewing agent locally and retain no terminal transcript."
}

preflight
banner "Sachkov Inside Telegram credentialed proof"

if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  PROOF_DISPOSAL_STATE="$(_existing TELEGRAM_PROOF_DISPOSAL_STATE || true)"
  if [[ "$PROOF_DISPOSAL_STATE" == "complete" ]]; then
    note "credentialed proof disposal is already complete; evidence was preserved"
    finish
    exit 0
  fi
  if [[ -n "$PROOF_DISPOSAL_STATE" ]]; then
    _STAGE_INDEX=12
    stage "Resume credential and temporary-resource disposal"
    complete_credential_disposal "$PROOF_DISPOSAL_STATE"
    finish
    exit 0
  fi
fi

stage "Scope and destinations"
say "This temporary proof writes secrets and provider identifiers only to ignored $ENV_FILE."
step "BotFather produces TELEGRAM_BOT_TOKEN; getMe verifies TELEGRAM_PROOF_BOT_ID and TELEGRAM_PROOF_BOT_USERNAME."
step "The closed chat produces TELEGRAM_CANONICAL_CHAT_ID; the temporary callback produces TELEGRAM_PROOF_WEBHOOK_URL."
step "Webhook and Platform integration credentials are written only to $ENV_FILE and matching temporary Platform configuration."
step "Redacted observations go to ignored .credentialed-proof/evidence.json; recovery input exists only in an ignored mode-0600 file removed after use and on exit."
step "A re-run safely reuses the stored bot/chat, archives prior redacted evidence, and starts with a fresh database-count baseline."
step "No GitHub secret, production environment, external message campaign, deploy, or production traffic is changed."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  if ! confirm "Are primary-owner Telegram, BotFather, and temporary Platform sessions ready?"; then
    warn "proof cancelled because required owner sessions are not ready"
    exit 1
  fi
  if ! confirm "Continue with this exact scope and these destinations?"; then
    warn "proof cancelled before any credential was captured"
    exit 1
  fi
fi

stage "BotFather identity"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  TELEGRAM_BOT_TOKEN="123456:non_secret_fixture_token_abcdefghijklmnopqrstuvwxyz"
  TELEGRAM_PROOF_BOT_USERNAME="inside_fixture_bot"
else
  EXISTING_BOT_TOKEN="$(_existing TELEGRAM_BOT_TOKEN || true)"
  EXISTING_BOT_USERNAME="$(_existing TELEGRAM_PROOF_BOT_USERNAME || true)"
  if [[ "$EXISTING_BOT_TOKEN" =~ ^[1-9][0-9]{5,}:[A-Za-z0-9_-]{20,}$ && -n "$EXISTING_BOT_USERNAME" ]]; then
    if ! confirm "Reuse the dedicated proof bot already stored in $ENV_FILE?"; then
      warn "dispose or archive the existing proof before creating a different bot"
      exit 1
    fi
    TELEGRAM_BOT_TOKEN="$EXISTING_BOT_TOKEN"
    TELEGRAM_PROOF_BOT_USERNAME="$EXISTING_BOT_USERNAME"
  else
    if [[ -f .credentialed-proof/evidence.json ]]; then
      warn "existing evidence has no reusable bot credential; archive it and start a new isolated proof"
      exit 1
    fi
    open_url "https://t.me/BotFather"
    step "Send /newbot, create a dedicated temporary Sachkov Inside proof bot, and copy its token."
    ask_secret TELEGRAM_BOT_TOKEN "Paste the temporary bot token (hidden):"
    step "Copy the exact username BotFather assigned, without changing the bot or token."
    ask_secret TELEGRAM_PROOF_BOT_USERNAME "Bot username (hidden):"
  fi
fi
if [[ ! "$TELEGRAM_BOT_TOKEN" =~ ^[1-9][0-9]{5,}:[A-Za-z0-9_-]{20,}$ ]]; then
  warn "token shape is not a Telegram Bot API token"
  exit 1
fi
TELEGRAM_PROOF_BOT_ID="${TELEGRAM_BOT_TOKEN%%:*}"
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env TELEGRAM_PROOF_BOT_ID "$TELEGRAM_PROOF_BOT_ID"
write_env TELEGRAM_PROOF_BOT_USERNAME "$TELEGRAM_PROOF_BOT_USERNAME"
probe begin-proof-run
probe verify-bot

stage "Closed chat and minimum administration"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  TELEGRAM_CANONICAL_CHAT_ID="-1001234567890"
else
  EXISTING_CHAT_ID="$(_existing TELEGRAM_CANONICAL_CHAT_ID || true)"
  if [[ "$EXISTING_CHAT_ID" =~ ^-[1-9][0-9]+$ && "$EXISTING_CHAT_ID" != "-1000000000000" ]]; then
    if ! confirm "Reuse the closed proof chat already stored in $ENV_FILE?"; then
      warn "dispose or archive the existing proof before selecting a different chat"
      exit 1
    fi
    TELEGRAM_CANONICAL_CHAT_ID="$EXISTING_CHAT_ID"
    step "Open the existing closed proof chat and inspect the dedicated bot's current administrator configuration."
  else
    open_url "https://web.telegram.org/"
    step "Create a temporary private group, add only the proof participants, and add the dedicated bot."
  fi
  step "Promote the bot to administrator; disable every client-assignable permission while retaining administrator status. can_manage_chat remains implied; getChat member defaults are recorded separately from admin-only rights."
  if ! confirm "Does the client now show every assignable administrator permission disabled?"; then
    warn "minimum administrator configuration is not confirmed"
    exit 1
  fi
  TELEGRAM_PROOF_MINIMUM_ADMIN_CONFIRMED=true
  if [[ -z "${TELEGRAM_CANONICAL_CHAT_ID:-}" ]]; then
    step "Send /proof_chat_id in that group so getUpdates can discover it before webhook setup."
    pause "Press Enter after the group update is visible"
    probe capture-chat-id
    TELEGRAM_CANONICAL_CHAT_ID="$(<.credentialed-proof/chat-id)"
    rm .credentialed-proof/chat-id
  fi
fi
write_env TELEGRAM_CANONICAL_CHAT_ID "$TELEGRAM_CANONICAL_CHAT_ID"
write_env TELEGRAM_PROOF_MINIMUM_ADMIN_CONFIRMED "${TELEGRAM_PROOF_MINIMUM_ADMIN_CONFIRMED:-true}"
probe verify-chat

stage "Temporary application and Platform seam"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  TELEGRAM_PROOF_WEBHOOK_URL="https://proof.invalid/webhooks/telegram"
  PLATFORM_EVIDENCE_DELIVERY_URL="https://platform-proof.invalid/integrations/telegram/v1/membership-evidence"
  PLATFORM_INTEGRATION_SECRET="non_secret_fixture_platform_link"
  PLATFORM_EVIDENCE_DELIVERY_SECRET="non_secret_fixture_evidence_delivery"
else
  step "Start the task database and Telegram application from this checkout; expose only /webhooks/telegram through a temporary HTTPS endpoint."
  ask_secret TELEGRAM_PROOF_WEBHOOK_URL "Full temporary HTTPS webhook URL (hidden):"
  step "Start the temporary Platform consumer and copy its Membership Evidence endpoint."
  ask_secret PLATFORM_EVIDENCE_DELIVERY_URL "Temporary Platform evidence URL (hidden):"
  step "Copy the matching temporary Platform→Telegram linking bearer."
  ask_secret PLATFORM_INTEGRATION_SECRET "PLATFORM_INTEGRATION_SECRET (hidden):"
  step "Copy the separate matching Telegram→Platform evidence bearer."
  ask_secret PLATFORM_EVIDENCE_DELIVERY_SECRET "PLATFORM_EVIDENCE_DELIVERY_SECRET (hidden):"
fi
TELEGRAM_WEBHOOK_SECRET="$(node -e 'process.stdout.write(require("node:crypto").randomBytes(32).toString("base64url"))')"
write_env TELEGRAM_PROOF_WEBHOOK_URL "$TELEGRAM_PROOF_WEBHOOK_URL"
write_env PLATFORM_EVIDENCE_DELIVERY_URL "$PLATFORM_EVIDENCE_DELIVERY_URL"
write_env PLATFORM_INTEGRATION_SECRET "$PLATFORM_INTEGRATION_SECRET"
write_env PLATFORM_EVIDENCE_DELIVERY_SECRET "$PLATFORM_EVIDENCE_DELIVERY_SECRET"
write_env PLATFORM_EVIDENCE_DELIVERY_MODE live
write_env TELEGRAM_DELIVERY_MODE live
write_env TELEGRAM_MEMBERSHIP_MODE live
write_env TELEGRAM_WEBHOOK_SECRET "$TELEGRAM_WEBHOOK_SECRET"
write_env WORKERS_ENABLED true
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  step "In the Telegram application terminal, export ENV_FILE='$ENV_FILE' and ENV_FILE_OVERRIDE=true, run pnpm db:migrate, then start or restart the application."
  step "Start or restart the temporary Platform consumer with the matching credentials shown in this scope."
  pause "Press Enter when both applications and the HTTPS endpoint are healthy"
fi
probe snapshot baseline

stage "Webhook contract"
step "Keep the application and HTTPS endpoint running. The probe sets only message, my_chat_member, and chat_member updates with the separate secret token."
probe configure-webhook
probe verify-webhook-auth
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  step "Send one ordinary message in the proof group and confirm it reaches the application."
  pause "Press Enter after the update is acknowledged"
fi

stage "Webhook auth, durability, retry, and deduplication"
step "Send synthetic no-PII updates to the callback with missing, wrong, and correct secret headers; missing/wrong must reject and correct must return 2xx only after inbox commit."
step "Repeat the same synthetic update_id and confirm the durable inbox remains unique."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  TELEGRAM_PROOF_RETRY_MARKER="inside-proof-retry-$(node -e 'process.stdout.write(require("node:crypto").randomBytes(8).toString("hex"))')"
  write_env TELEGRAM_PROOF_RETRY_MARKER "$TELEGRAM_PROOF_RETRY_MARKER"
  write_env WORKERS_ENABLED false
  step "Configure the temporary HTTPS edge to return HTTP 503 without forwarding, then send this exact non-secret marker in the proof chat: $TELEGRAM_PROOF_RETRY_MARKER"
  pause "Press Enter after getWebhookInfo reports the HTTP 503 delivery failure"
fi
probe observe-webhook-outage
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  step "Restore forwarding to the callback with WORKERS_ENABLED=false and do not send the marker again."
  pause "Press Enter after Telegram has retried the failed marker"
fi
probe verify-webhook-recovered
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  write_env WORKERS_ENABLED true
  step "Restart with WORKERS_ENABLED=true so the durably captured marker can be processed and redacted."
  pause "Press Enter after the worker has processed the marker"
fi
probe snapshot webhook-recovered

stage "Ordinary and tokenized /start"
step "In a private chat with the bot, run ordinary /start and confirm Contactability plus a durable response delivery."
step "From authenticated temporary Platform Accounts, exercise a valid token, expired token, replay, concurrent consume, same-identity repeat, and conflicting Account."
step "Confirm no raw token, username, email, or provider payload appears in the database or evidence file."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after all linking outcomes have been observed"
fi
probe snapshot linking-corpus

stage "Membership events and reconciliation"
step "Observe member/restricted/left/kicked or other reachable statuses and record the normalized outcome, not the raw identity."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after the reachable status corpus is complete"
fi
probe snapshot membership-status-corpus
step "Remove the linked subject and prove the newer observation denies access."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after removal is observed"
fi
probe snapshot membership-removed
step "Rejoin the linked subject and prove the newer observation restores access."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after rejoin is observed"
fi
probe snapshot membership-rejoined
step "Temporarily exclude chat_member from allowed_updates, remove the subject, and capture the unchanged pre-reconciliation revision."
probe suppress-membership-events
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter immediately after the removal, before the reconciliation cadence"
fi
probe snapshot removal-event-suppressed
probe configure-webhook
step "With exact allowed_updates restored, wait for reconciliation to repair the missed removal without extending stale positive evidence."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after reconciliation has repaired the missed removal"
fi
probe snapshot reconciliation-repaired

stage "Administrator loss and provider outage"
step "Demote the bot, then trigger a membership read."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after the demotion and failed membership read"
fi
probe observe-chat-demoted
probe snapshot administrator-demoted
step "Restore the same minimum administrator configuration and trigger a newer membership read."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after the administrator restoration and newer observation"
fi
probe verify-chat
probe snapshot administrator-restored
step "Interrupt provider reachability, exercise access through the five-minute boundary, and confirm it expires closed."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after the provider outage has been observed"
fi
probe snapshot provider-outage
step "Restore provider reachability and trigger a new membership observation."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after provider recovery"
fi
probe snapshot provider-restored

stage "Blocked send and restored contactability"
step "Block the bot from the temporary user and trigger a response; the Bot API rejection remains a delivery diagnostic only."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after the blocked-send attempt"
fi
probe snapshot contact-blocked
step "Unblock the bot and send a new /start; confirm Contactability and delivery recover without inferring Membership."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after contactability recovery"
fi
probe snapshot contact-restored

stage "Owner-only identity recovery rehearsal"
say "Use only the temporary conflicting Accounts created in this proof. No direct SQL edit is allowed."
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  note "dry-run: skipped owner recovery because fixture references are intentionally absent"
else
  ask RECOVERY_REF "Unique recovery audit reference:"
  ask OPERATOR_REF "Owner/operator reference:"
  ask REASON_REF "Issue/change reference:"
  ask_secret TELEGRAM_IDENTITY_REF "TelegramIdentity reference (hidden):"
  ask_secret SOURCE_ACCOUNT_REF "Current source Principal reference (hidden):"
  ask_secret TARGET_ACCOUNT_REF "Target Principal reference (hidden):"
  ask_secret TARGET_LINK_TRANSACTION_REF "Target conflict transaction reference (hidden):"
  CONFIRMED_SOURCE_ACCOUNT_REF=""
  CONFIRMED_TARGET_ACCOUNT_REF=""
  write_recovery_input
  pnpm owner:recover-identity --dry-run < "$RECOVERY_INPUT_FILE"
  step "Compare the printed source/target fingerprints with the separately recorded owner values."
  if ! confirm "Execute this transfer on the temporary recovery fixture?"; then
    warn "actual recovery rehearsal is incomplete"
    exit 1
  fi
  ask_secret CONFIRMED_SOURCE_ACCOUNT_REF "Re-enter the source Principal reference (hidden):"
  ask_secret CONFIRMED_TARGET_ACCOUNT_REF "Re-enter the target Principal reference (hidden):"
  write_recovery_input
  pnpm owner:recover-identity --execute < "$RECOVERY_INPUT_FILE"
  remove_recovery_input
  unset TELEGRAM_IDENTITY_REF SOURCE_ACCOUNT_REF TARGET_ACCOUNT_REF TARGET_LINK_TRANSACTION_REF
  unset CONFIRMED_SOURCE_ACCOUNT_REF CONFIRMED_TARGET_ACCOUNT_REF
fi
probe snapshot owner-recovery

stage "Redacted evidence handoff"
probe snapshot final
step "Inspect .credentialed-proof/evidence.json locally; never paste it into an issue or PR."
step "Do not start disposal if any acceptance scenario is missing; rerun the relevant stage instead."
step "The final reviewer handoff happens only after the disposal stage adds its redacted observations."

stage "Credential and temporary-resource disposal"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  note "dry-run: skipped external disposal and left only non-secret fixture values in the temporary ENV_FILE"
else
  complete_credential_disposal ""
fi

finish
