services:
  migrations:
    image: ${PLATFORM_API_BUILD_IMAGE:?Set PLATFORM_API_BUILD_IMAGE}

  api:
    image: ${PLATFORM_API_BUILD_IMAGE:?Set PLATFORM_API_BUILD_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      target: api-production
      args:
        SOURCE_REVISION: ${SOURCE_REVISION:-local}

  web:
    image: ${PLATFORM_WEB_BUILD_IMAGE:?Set PLATFORM_WEB_BUILD_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      target: web-production
      args:
        SOURCE_REVISION: ${SOURCE_REVISION:-local}
