packages:
  - apps/*
engineStrict: true
saveExact: true
strictPeerDependencies: true
minimumReleaseAge: 1440
allowBuilds:
  '@scarf/scarf': false
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
