Match User inside-deploy
    AllowAgentForwarding no
    AllowTcpForwarding no
    ForceCommand /usr/local/libexec/inside/inside-deploy-command
    PasswordAuthentication no
    PermitTTY no
    PermitTunnel no
    X11Forwarding no
