export {
  fillOfferTerms,
  guidePageSchema,
  guidePresentations,
  readGuidePageCard,
  readGuideProductPage,
  resolveGuidePresentation,
  type GuidePage,
  type GuidePageBlock,
  type GuidePageBlockOf,
  type GuidePageCard,
  type GuidePresentation,
  type GuideProductPage,
  type OfferTerms,
  type PresentationWarning,
} from "./model/guide-page";
