// Code generated by internal/contracts/generate; DO NOT EDIT.

package contracts

var schemaDocuments = map[Kind][]byte{
	CaseSpec: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.case-spec.v1.schema.json",
  "title": "Inside Workshop CaseSpec v1",
  "x-inside-byte-limits": {
    "document": 1048576
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "caseId",
    "caseVersion",
    "evaluatorVersion",
    "title",
    "learningFacts",
    "brief",
    "variants",
    "scenarios",
    "observableThresholds",
    "supportedHosts",
    "materials",
    "revealPolicy"
  ],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.case-spec.v1"
    },
    "caseId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "caseVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    },
    "evaluatorVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    },
    "title": {
      "type": "string",
      "minLength": 1,
      "maxLength": 160
    },
    "learningFacts": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 500
      }
    },
    "brief": {
      "type": "object",
      "additionalProperties": false,
      "required": ["summary", "constraints"],
      "properties": {
        "summary": {
          "type": "string",
          "minLength": 1,
          "maxLength": 10000
        },
        "constraints": {
          "type": "array",
          "minItems": 1,
          "maxItems": 64,
          "uniqueItems": true,
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1000
          }
        }
      }
    },
    "variants": {
      "type": "array",
      "minItems": 1,
      "maxItems": 8,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "displayName",
          "runtime",
          "starterArtifactSha256",
          "evaluatorBundleSha256"
        ],
        "properties": {
          "id": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
          },
          "displayName": {
            "type": "string",
            "minLength": 1,
            "maxLength": 120
          },
          "runtime": {
            "type": "string",
            "minLength": 1,
            "maxLength": 120
          },
          "starterArtifactSha256": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/sha256"
          },
          "evaluatorBundleSha256": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/sha256"
          }
        }
      }
    },
    "scenarios": {
      "type": "array",
      "minItems": 1,
      "maxItems": 64,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["id", "title", "required"],
        "properties": {
          "id": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "maxLength": 160
          },
          "required": {
            "type": "boolean"
          }
        }
      }
    },
    "observableThresholds": {
      "type": "array",
      "maxItems": 64,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["id", "operator", "value", "unit"],
        "properties": {
          "id": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
          },
          "operator": {
            "enum": ["eq", "gte", "lte"]
          },
          "value": {
            "type": "number"
          },
          "unit": {
            "type": "string",
            "minLength": 1,
            "maxLength": 40
          }
        }
      }
    },
    "supportedHosts": {
      "type": "array",
      "minItems": 1,
      "maxItems": 3,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/supportedHost"
      }
    },
    "materials": {
      "type": "array",
      "maxItems": 64,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["materialId", "role", "order", "releasePolicy"],
        "properties": {
          "materialId": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
          },
          "role": {
            "enum": ["prerequisite", "reference", "hint", "solution", "alternative"]
          },
          "order": {
            "type": "integer",
            "minimum": 0,
            "maximum": 1000
          },
          "releasePolicy": {
            "enum": ["always", "after_attempt", "after_attempt_or_warned_early_reveal"]
          }
        }
      }
    },
    "revealPolicy": {
      "const": "after_attempt_or_warned_early_reveal"
    }
  },
  "$defs": {
    "supportedHost": {
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "required": ["os", "arch"],
          "properties": {
            "os": { "const": "darwin" },
            "arch": { "const": "arm64" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "required": ["os", "arch"],
          "properties": {
            "os": { "const": "linux" },
            "arch": { "const": "amd64" }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "required": ["os", "arch"],
          "properties": {
            "os": { "const": "windows" },
            "arch": { "const": "amd64" }
          }
        }
      ]
    }
  }
}
`),
	AssignmentManifest: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.assignment-manifest.v1.schema.json",
  "title": "Inside Workshop assignment manifest v1",
  "x-inside-byte-limits": {
    "document": 262144
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "platformOrigin",
    "assignmentId",
    "caseId",
    "caseVersion",
    "variantId",
    "evaluatorVersion",
    "repositorySlug",
    "defaultBranch",
    "starterArtifactSha256",
    "evaluatorBundle",
    "scenarios",
    "supportedHosts",
    "evaluationTimeoutSeconds"
  ],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.assignment-manifest.v1"
    },
    "platformOrigin": {
      "type": "string",
      "format": "uri"
    },
    "assignmentId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "caseId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "caseVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    },
    "variantId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "evaluatorVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    },
    "repositorySlug": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$",
      "maxLength": 200
    },
    "defaultBranch": {
      "const": "main"
    },
    "starterArtifactSha256": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/sha256"
    },
    "evaluatorBundle": {
      "type": "object",
      "additionalProperties": false,
      "required": ["url", "sha256", "maxBytes"],
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "sha256": {
          "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/sha256"
        },
        "maxBytes": {
          "type": "integer",
          "minimum": 1,
          "maximum": 33554432
        }
      }
    },
    "scenarios": {
      "type": "array",
      "minItems": 1,
      "maxItems": 64,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["id", "required"],
        "properties": {
          "id": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
          },
          "required": {
            "type": "boolean"
          }
        }
      }
    },
    "supportedHosts": {
      "type": "array",
      "minItems": 1,
      "maxItems": 3,
      "uniqueItems": true,
      "items": {
        "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.case-spec.v1.schema.json#/$defs/supportedHost"
      }
    },
    "evaluationTimeoutSeconds": {
      "type": "integer",
      "minimum": 1,
      "maximum": 3600
    }
  }
}
`),
	EvaluationReport: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluation-report.v1.schema.json",
  "title": "Inside Workshop evaluation report v1",
  "x-inside-byte-limits": {
    "document": 262144,
    "diagnosticMessage": 2048,
    "diagnosticsTotal": 131072
  },
  "x-inside-diagnostic-messages": {
    "scenario_failed": "The declared scenario did not pass.",
    "compose_failed": "The evaluator topology exited before all scenarios completed.",
    "evaluation_timeout": "The evaluator reached its bounded execution timeout.",
    "evaluation_interrupted": "The evaluator was interrupted before completion.",
    "invalid_result": "The evaluator produced an invalid structured result."
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "reportVersion",
    "assignmentId",
    "caseId",
    "caseVersion",
    "variantId",
    "evaluatorVersion",
    "commitSha",
    "environment",
    "startedAt",
    "finishedAt",
    "scenarios"
  ],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.evaluation-report.v1"
    },
    "reportVersion": {
      "const": "1"
    },
    "assignmentId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "caseId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "caseVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    },
    "variantId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "evaluatorVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    },
    "commitSha": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/gitSha"
    },
    "environment": {
      "type": "object",
      "additionalProperties": false,
      "required": ["os", "arch", "dockerVersion", "composeVersion"],
      "properties": {
        "os": { "type": "string", "minLength": 1, "maxLength": 32 },
        "arch": { "type": "string", "minLength": 1, "maxLength": 32 },
        "dockerVersion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },
        "composeVersion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        }
      }
    },
    "startedAt": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/timestamp"
    },
    "finishedAt": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/timestamp"
    },
    "scenarios": {
      "type": "array",
      "minItems": 1,
      "maxItems": 64,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["id", "status", "durationMilliseconds"],
        "properties": {
          "id": {
            "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
          },
          "status": {
            "enum": ["passed", "failed"]
          },
          "durationMilliseconds": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3600000
          },
          "diagnostic": {
            "type": "object",
            "additionalProperties": false,
            "required": ["code", "message"],
            "properties": {
              "code": {
                "enum": [
                  "scenario_failed",
                  "compose_failed",
                  "evaluation_timeout",
                  "evaluation_interrupted",
                  "invalid_result"
                ]
              },
              "message": {
                "type": "string",
                "minLength": 1,
                "maxLength": 2048
              }
            }
          }
        },
        "allOf": [
          {
            "if": {
              "properties": { "status": { "const": "failed" } },
              "required": ["status"]
            },
            "then": {
              "properties": { "diagnostic": true },
              "required": ["diagnostic"]
            }
          },
          {
            "if": {
              "properties": { "status": { "const": "passed" } },
              "required": ["status"]
            },
            "then": {
              "not": { "required": ["diagnostic"] }
            }
          }
        ]
      }
    }
  }
}
`),
	SourceSnapshot: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.source-snapshot.v1.schema.json",
  "title": "Inside Workshop source snapshot v1",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "assignmentId",
    "repositoryId",
    "commitSha",
    "treeSha",
    "archiveSha256",
    "compressedBytes",
    "expandedBytes",
    "capturedAt"
  ],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.source-snapshot.v1"
    },
    "assignmentId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "repositoryId": {
      "type": "string",
      "pattern": "^[1-9][0-9]{0,19}$"
    },
    "commitSha": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/gitSha"
    },
    "treeSha": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/gitSha"
    },
    "archiveSha256": {
	  "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/sha256"
    },
    "compressedBytes": {
      "type": "integer",
      "minimum": 1,
      "maximum": 52428800
    },
    "expandedBytes": {
      "type": "integer",
      "minimum": 1,
      "maximum": 209715200
    },
    "capturedAt": {
	  "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/timestamp"
    }
  }
}
`),
	DeviceAuthorizationRequestContract: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-authorization-request.v1.schema.json",
  "title": "Inside Workshop evaluator device authorization request v1",
  "x-inside-byte-limits": { "document": 4096 },
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "assignmentId", "caseVersion", "evaluatorVersion"],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.evaluator-device-authorization-request.v1"
    },
    "assignmentId": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueId"
    },
    "caseVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    },
    "evaluatorVersion": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueVersion"
    }
  }
}
`),
	DeviceAuthorizationResponseContract: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-authorization-response.v1.schema.json",
  "title": "Inside Workshop evaluator device authorization response v1",
  "x-inside-byte-limits": { "document": 65536 },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "deviceCode",
    "userCode",
    "verificationUrl",
    "expiresInSeconds",
    "intervalSeconds"
  ],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.evaluator-device-authorization-response.v1"
    },
    "deviceCode": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueSecret"
    },
    "userCode": {
      "type": "string",
      "pattern": "^[A-Z0-9-]{1,64}$"
    },
    "verificationUrl": {
      "type": "string",
      "format": "uri"
    },
    "expiresInSeconds": {
      "type": "integer",
      "minimum": 1,
      "maximum": 600
    },
    "intervalSeconds": {
      "type": "integer",
      "minimum": 1,
      "maximum": 30
    }
  }
}
`),
	DeviceTokenRequestContract: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-token-request.v1.schema.json",
  "title": "Inside Workshop evaluator device token request v1",
  "x-inside-byte-limits": { "document": 1024 },
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "deviceCode"],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.evaluator-device-token-request.v1"
    },
    "deviceCode": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueSecret"
    }
  }
}
`),
	DeviceTokenResponseContract: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-token-response.v1.schema.json",
  "title": "Inside Workshop evaluator device token response v1",
  "x-inside-byte-limits": { "document": 65536 },
  "x-inside-slow-down-step-seconds": 1,
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "status"],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.evaluator-device-token-response.v1"
    },
    "status": {
      "enum": ["pending", "slow_down", "authorized", "denied", "expired"]
    },
    "reportToken": {
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/opaqueSecret"
    },
    "assignmentManifestSha256": {
      "$comment": "SHA-256 of inside.workshop.canonical-json.v1 encoding of the validated Assignment manifest.",
      "$ref": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json#/$defs/sha256"
    },
    "intervalSeconds": {
      "type": "integer",
      "minimum": 1,
      "maximum": 30
    }
  },
  "allOf": [
    {
      "if": {
        "properties": { "status": { "const": "authorized" } },
        "required": ["status"]
      },
      "then": {
        "required": ["reportToken", "assignmentManifestSha256"]
      },
      "else": {
        "not": {
          "anyOf": [
            { "required": ["reportToken"] },
            { "required": ["assignmentManifestSha256"] }
          ]
        }
      }
    },
    {
      "if": {
        "properties": { "status": { "const": "slow_down" } },
        "required": ["status"]
      },
      "else": {
        "not": { "required": ["intervalSeconds"] }
      }
    }
  ]
}
`),
	EvaluatorReportAcceptanceContract: []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-report-acceptance.v1.schema.json",
  "title": "Inside Workshop evaluator report acceptance v1",
  "x-inside-byte-limits": { "document": 4096 },
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "accepted"],
  "properties": {
    "schemaVersion": {
      "const": "inside.workshop.evaluator-report-acceptance.v1"
    },
    "accepted": {
      "const": true
    }
  }
}
`),
}

var supportingSchemaDocuments = map[string][]byte{
	"https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json": []byte(`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://inside.sachkov.dev/contracts/workshop/inside.workshop.primitives.v1.schema.json",
  "title": "Inside Workshop shared primitives v1",
  "$defs": {
    "opaqueId": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
    },
    "opaqueVersion": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "sha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "gitSha": {
      "type": "string",
      "pattern": "^[a-f0-9]{40}$"
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "opaqueSecret": {
      "type": "string",
      "pattern": "^[A-Za-z0-9._~-]{1,512}$"
    }
  }
}
`),
}

var schemaLocations = map[Kind]string{
	CaseSpec:                            "https://inside.sachkov.dev/contracts/workshop/inside.workshop.case-spec.v1.schema.json",
	AssignmentManifest:                  "https://inside.sachkov.dev/contracts/workshop/inside.workshop.assignment-manifest.v1.schema.json",
	EvaluationReport:                    "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluation-report.v1.schema.json",
	SourceSnapshot:                      "https://inside.sachkov.dev/contracts/workshop/inside.workshop.source-snapshot.v1.schema.json",
	DeviceAuthorizationRequestContract:  "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-authorization-request.v1.schema.json",
	DeviceAuthorizationResponseContract: "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-authorization-response.v1.schema.json",
	DeviceTokenRequestContract:          "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-token-request.v1.schema.json",
	DeviceTokenResponseContract:         "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-device-token-response.v1.schema.json",
	EvaluatorReportAcceptanceContract:   "https://inside.sachkov.dev/contracts/workshop/inside.workshop.evaluator-report-acceptance.v1.schema.json",
}

var contractByteLimits = map[Kind]map[string]int64{
	CaseSpec: {
		"document": 1048576,
	},
	AssignmentManifest: {
		"document": 262144,
	},
	EvaluationReport: {
		"diagnosticMessage": 2048,
		"diagnosticsTotal":  131072,
		"document":          262144,
	},
	DeviceAuthorizationRequestContract: {
		"document": 4096,
	},
	DeviceAuthorizationResponseContract: {
		"document": 65536,
	},
	DeviceTokenRequestContract: {
		"document": 1024,
	},
	DeviceTokenResponseContract: {
		"document": 65536,
	},
	EvaluatorReportAcceptanceContract: {
		"document": 4096,
	},
}

const (
	CaseSchemaVersion                               = "inside.workshop.case-spec.v1"
	ManifestSchemaVersion                           = "inside.workshop.assignment-manifest.v1"
	ReportSchemaVersion                             = "inside.workshop.evaluation-report.v1"
	SourceSnapshotDocumentSchemaVersion             = "inside.workshop.source-snapshot.v1"
	DeviceAuthorizationRequestSchemaVersion         = "inside.workshop.evaluator-device-authorization-request.v1"
	DeviceAuthorizationResponseSchemaVersion        = "inside.workshop.evaluator-device-authorization-response.v1"
	DeviceTokenRequestSchemaVersion                 = "inside.workshop.evaluator-device-token-request.v1"
	DeviceTokenResponseSchemaVersion                = "inside.workshop.evaluator-device-token-response.v1"
	EvaluatorReportAcceptanceSchemaVersion          = "inside.workshop.evaluator-report-acceptance.v1"
	ReportVersion                                   = "1"
	ReportScenarioStatusPassed                      = "passed"
	ReportScenarioStatusFailed                      = "failed"
	DeviceTokenStatusPending                        = "pending"
	DeviceTokenStatusSlowDown                       = "slow_down"
	DeviceTokenStatusAuthorized                     = "authorized"
	DeviceTokenStatusDenied                         = "denied"
	DeviceTokenStatusExpired                        = "expired"
	DeviceTokenSlowDownStepSeconds            int64 = 1
	ReportScenarioDurationMaximumMilliseconds int64 = 3600000
)

const (
	DiagnosticCodeScenarioFailed        = "scenario_failed"
	DiagnosticCodeComposeFailed         = "compose_failed"
	DiagnosticCodeEvaluationTimeout     = "evaluation_timeout"
	DiagnosticCodeEvaluationInterrupted = "evaluation_interrupted"
	DiagnosticCodeInvalidResult         = "invalid_result"
)

var contractDiagnosticMessages = map[string]string{
	"compose_failed":         "The evaluator topology exited before all scenarios completed.",
	"evaluation_interrupted": "The evaluator was interrupted before completion.",
	"evaluation_timeout":     "The evaluator reached its bounded execution timeout.",
	"invalid_result":         "The evaluator produced an invalid structured result.",
	"scenario_failed":        "The declared scenario did not pass.",
}

var contractSupportedHosts = map[string]struct{}{
	"darwin/arm64":  {},
	"linux/amd64":   {},
	"windows/amd64": {},
}

type Case struct {
	Brief                CaseBrief                      `json:"brief"`
	CaseID               string                         `json:"caseId"`
	CaseVersion          string                         `json:"caseVersion"`
	EvaluatorVersion     string                         `json:"evaluatorVersion"`
	LearningFacts        []string                       `json:"learningFacts"`
	Materials            []CaseMaterialsItem            `json:"materials"`
	ObservableThresholds []CaseObservableThresholdsItem `json:"observableThresholds"`
	RevealPolicy         string                         `json:"revealPolicy"`
	Scenarios            []CaseScenariosItem            `json:"scenarios"`
	SchemaVersion        string                         `json:"schemaVersion"`
	SupportedHosts       []CaseSupportedHostsItem       `json:"supportedHosts"`
	Title                string                         `json:"title"`
	Variants             []CaseVariantsItem             `json:"variants"`
}

type CaseBrief struct {
	Constraints []string `json:"constraints"`
	Summary     string   `json:"summary"`
}

type CaseMaterialsItem struct {
	MaterialID    string `json:"materialId"`
	Order         int64  `json:"order"`
	ReleasePolicy string `json:"releasePolicy"`
	Role          string `json:"role"`
}

type CaseObservableThresholdsItem struct {
	ID       string  `json:"id"`
	Operator string  `json:"operator"`
	Unit     string  `json:"unit"`
	Value    float64 `json:"value"`
}

type CaseScenariosItem struct {
	ID       string `json:"id"`
	Required bool   `json:"required"`
	Title    string `json:"title"`
}

type CaseSupportedHostsItem struct {
	Arch string `json:"arch"`
	OS   string `json:"os"`
}

type CaseVariantsItem struct {
	DisplayName           string `json:"displayName"`
	EvaluatorBundleSHA256 string `json:"evaluatorBundleSha256"`
	ID                    string `json:"id"`
	Runtime               string `json:"runtime"`
	StarterArtifactSHA256 string `json:"starterArtifactSha256"`
}

type Manifest struct {
	AssignmentID             string                       `json:"assignmentId"`
	CaseID                   string                       `json:"caseId"`
	CaseVersion              string                       `json:"caseVersion"`
	DefaultBranch            string                       `json:"defaultBranch"`
	EvaluationTimeoutSeconds int64                        `json:"evaluationTimeoutSeconds"`
	EvaluatorBundle          ManifestEvaluatorBundle      `json:"evaluatorBundle"`
	EvaluatorVersion         string                       `json:"evaluatorVersion"`
	PlatformOrigin           string                       `json:"platformOrigin"`
	RepositorySlug           string                       `json:"repositorySlug"`
	Scenarios                []ManifestScenariosItem      `json:"scenarios"`
	SchemaVersion            string                       `json:"schemaVersion"`
	StarterArtifactSHA256    string                       `json:"starterArtifactSha256"`
	SupportedHosts           []ManifestSupportedHostsItem `json:"supportedHosts"`
	VariantID                string                       `json:"variantId"`
}

type ManifestEvaluatorBundle struct {
	MaxBytes int64  `json:"maxBytes"`
	SHA256   string `json:"sha256"`
	URL      string `json:"url"`
}

type ManifestScenariosItem struct {
	ID       string `json:"id"`
	Required bool   `json:"required"`
}

type ManifestSupportedHostsItem struct {
	Arch string `json:"arch"`
	OS   string `json:"os"`
}

type Report struct {
	AssignmentID     string                `json:"assignmentId"`
	CaseID           string                `json:"caseId"`
	CaseVersion      string                `json:"caseVersion"`
	CommitSHA        string                `json:"commitSha"`
	Environment      ReportEnvironment     `json:"environment"`
	EvaluatorVersion string                `json:"evaluatorVersion"`
	FinishedAt       string                `json:"finishedAt"`
	ReportVersion    string                `json:"reportVersion"`
	Scenarios        []ReportScenariosItem `json:"scenarios"`
	SchemaVersion    string                `json:"schemaVersion"`
	StartedAt        string                `json:"startedAt"`
	VariantID        string                `json:"variantId"`
}

type ReportEnvironment struct {
	Arch           string `json:"arch"`
	ComposeVersion string `json:"composeVersion"`
	DockerVersion  string `json:"dockerVersion"`
	OS             string `json:"os"`
}

type ReportScenariosItem struct {
	Diagnostic           *ReportScenariosItemDiagnostic `json:"diagnostic,omitempty"`
	DurationMilliseconds int64                          `json:"durationMilliseconds"`
	ID                   string                         `json:"id"`
	Status               string                         `json:"status"`
}

type ReportScenariosItemDiagnostic struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type SourceSnapshotDocument struct {
	ArchiveSHA256   string `json:"archiveSha256"`
	AssignmentID    string `json:"assignmentId"`
	CapturedAt      string `json:"capturedAt"`
	CommitSHA       string `json:"commitSha"`
	CompressedBytes int64  `json:"compressedBytes"`
	ExpandedBytes   int64  `json:"expandedBytes"`
	RepositoryID    string `json:"repositoryId"`
	SchemaVersion   string `json:"schemaVersion"`
	TreeSHA         string `json:"treeSha"`
}

type DeviceAuthorizationRequest struct {
	AssignmentID     string `json:"assignmentId"`
	CaseVersion      string `json:"caseVersion"`
	EvaluatorVersion string `json:"evaluatorVersion"`
	SchemaVersion    string `json:"schemaVersion"`
}

type DeviceAuthorizationResponse struct {
	DeviceCode       string `json:"deviceCode"`
	ExpiresInSeconds int64  `json:"expiresInSeconds"`
	IntervalSeconds  int64  `json:"intervalSeconds"`
	SchemaVersion    string `json:"schemaVersion"`
	UserCode         string `json:"userCode"`
	VerificationURL  string `json:"verificationUrl"`
}

type DeviceTokenRequest struct {
	DeviceCode    string `json:"deviceCode"`
	SchemaVersion string `json:"schemaVersion"`
}

type DeviceTokenResponse struct {
	AssignmentManifestSHA256 *string `json:"assignmentManifestSha256,omitempty"`
	IntervalSeconds          *int64  `json:"intervalSeconds,omitempty"`
	ReportToken              *string `json:"reportToken,omitempty"`
	SchemaVersion            string  `json:"schemaVersion"`
	Status                   string  `json:"status"`
}

type EvaluatorReportAcceptance struct {
	Accepted      bool   `json:"accepted"`
	SchemaVersion string `json:"schemaVersion"`
}
