export const WORKSHOP_MATERIAL_ACCESS = Symbol("WORKSHOP_MATERIAL_ACCESS");
export const WORKSHOP_MATERIAL_PROTECTION = Symbol(
  "WORKSHOP_MATERIAL_PROTECTION",
);
export const WORKSHOP_ENTITLEMENTS = Symbol("WORKSHOP_ENTITLEMENTS");
