package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

const primitivesFilename = "inside.workshop.primitives.v1.schema.json"

var schemaFiles = []struct {
	kind     string
	filename string
	typeName string
}{
	{"CaseSpec", "inside.workshop.case-spec.v1.schema.json", "Case"},
	{"AssignmentManifest", "inside.workshop.assignment-manifest.v1.schema.json", "Manifest"},
	{"EvaluationReport", "inside.workshop.evaluation-report.v1.schema.json", "Report"},
	{"SourceSnapshot", "inside.workshop.source-snapshot.v1.schema.json", "SourceSnapshotDocument"},
	{"DeviceAuthorizationRequestContract", "inside.workshop.evaluator-device-authorization-request.v1.schema.json", "DeviceAuthorizationRequest"},
	{"DeviceAuthorizationResponseContract", "inside.workshop.evaluator-device-authorization-response.v1.schema.json", "DeviceAuthorizationResponse"},
	{"DeviceTokenRequestContract", "inside.workshop.evaluator-device-token-request.v1.schema.json", "DeviceTokenRequest"},
	{"DeviceTokenResponseContract", "inside.workshop.evaluator-device-token-response.v1.schema.json", "DeviceTokenResponse"},
	{"EvaluatorReportAcceptanceContract", "inside.workshop.evaluator-report-acceptance.v1.schema.json", "EvaluatorReportAcceptance"},
}

type loadedSchema struct {
	kind     string
	filename string
	typeName string
	contents []byte
	document map[string]any
}

type goField struct {
	name     string
	typeName string
	jsonName string
	optional bool
}

type goStruct struct {
	name   string
	fields []goField
}

func main() {
	contractsDirectory := flag.String("contracts", "../../../../contracts/workshop", "canonical contract directory")
	outputFilename := flag.String("output", "schemas_gen.go", "generated Go output")
	check := flag.Bool("check", false, "verify output without changing it")
	flag.Parse()

	generated, err := generate(*contractsDirectory)
	if err != nil {
		fatal(err)
	}
	if *check {
		existing, readErr := os.ReadFile(*outputFilename)
		if readErr != nil {
			fatal(fmt.Errorf("read generated schemas: %w", readErr))
		}
		if !bytes.Equal(existing, generated) {
			fatal(fmt.Errorf("%s is stale; run pnpm workshop:evaluator:generate", *outputFilename))
		}
		return
	}
	if err := os.WriteFile(*outputFilename, generated, 0o644); err != nil {
		fatal(fmt.Errorf("write generated schemas: %w", err))
	}
}

func generate(contractsDirectory string) ([]byte, error) {
	primitivesContents, err := os.ReadFile(filepath.Join(contractsDirectory, primitivesFilename))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", primitivesFilename, err)
	}
	var primitivesDocument map[string]any
	if err := json.Unmarshal(primitivesContents, &primitivesDocument); err != nil {
		return nil, fmt.Errorf("decode %s: %w", primitivesFilename, err)
	}
	primitivesID, err := schemaID(primitivesDocument)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", primitivesFilename, err)
	}
	documentsByID := map[string]map[string]any{primitivesID: primitivesDocument}

	schemas := make([]loadedSchema, 0, len(schemaFiles))
	for _, schemaFile := range schemaFiles {
		filename := filepath.Join(contractsDirectory, schemaFile.filename)
		contents, err := os.ReadFile(filename)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", schemaFile.filename, err)
		}
		var document map[string]any
		if err := json.Unmarshal(contents, &document); err != nil {
			return nil, fmt.Errorf("decode %s: %w", schemaFile.filename, err)
		}
		if bytes.Contains(contents, []byte("`")) {
			return nil, fmt.Errorf("%s contains a backtick and cannot be embedded", schemaFile.filename)
		}
		id, idErr := schemaID(document)
		if idErr != nil {
			return nil, fmt.Errorf("%s: %w", schemaFile.filename, idErr)
		}
		documentsByID[id] = document
		schemas = append(schemas, loadedSchema{
			kind:     schemaFile.kind,
			filename: schemaFile.filename,
			typeName: schemaFile.typeName,
			contents: contents,
			document: document,
		})
	}

	var source strings.Builder
	source.WriteString("// Code generated by internal/contracts/generate; DO NOT EDIT.\n\n")
	source.WriteString("package contracts\n\n")
	source.WriteString("var schemaDocuments = map[Kind][]byte{\n")
	for _, schema := range schemas {
		fmt.Fprintf(&source, "\t%s: []byte(`%s`),\n", schema.kind, schema.contents)
	}
	source.WriteString("}\n\n")
	fmt.Fprintf(
		&source,
		"var supportingSchemaDocuments = map[string][]byte{\n\t%q: []byte(`%s`),\n}\n\n",
		primitivesID,
		primitivesContents,
	)
	source.WriteString("var schemaLocations = map[Kind]string{\n")
	for _, schema := range schemas {
		id, idErr := schemaID(schema.document)
		if idErr != nil {
			return nil, fmt.Errorf("%s: %w", schema.filename, idErr)
		}
		fmt.Fprintf(&source, "\t%s: %q,\n", schema.kind, id)
	}
	source.WriteString("}\n\n")

	source.WriteString("var contractByteLimits = map[Kind]map[string]int64{\n")
	for _, schema := range schemas {
		limits, err := parseByteLimits(schema.document)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", schema.filename, err)
		}
		if len(limits) == 0 {
			continue
		}
		fmt.Fprintf(&source, "\t%s: {\n", schema.kind)
		names := sortedKeys(limits)
		for _, name := range names {
			fmt.Fprintf(&source, "\t\t%q: %d,\n", name, limits[name])
		}
		source.WriteString("\t},\n")
	}
	source.WriteString("}\n\n")
	if err := writeContractPolicies(&source, schemas); err != nil {
		return nil, err
	}

	for _, schema := range schemas {
		structs, err := inferStructs(schema.document, schema.typeName, documentsByID)
		if err != nil {
			return nil, fmt.Errorf("infer Go types from %s: %w", schema.filename, err)
		}
		for _, value := range structs {
			fmt.Fprintf(&source, "type %s struct {\n", value.name)
			for _, field := range value.fields {
				fieldType := field.typeName
				jsonTag := field.jsonName
				if field.optional {
					if !strings.HasPrefix(fieldType, "[]") {
						fieldType = "*" + fieldType
					}
					jsonTag += ",omitempty"
				}
				fmt.Fprintf(&source, "\t%s %s `json:%q`\n", field.name, fieldType, jsonTag)
			}
			source.WriteString("}\n\n")
		}
	}

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func writeContractPolicies(source *strings.Builder, schemas []loadedSchema) error {
	source.WriteString("const (\n")
	for _, schema := range schemas {
		version, err := stringPropertyConst(schema.document, "schemaVersion")
		if err != nil {
			return fmt.Errorf("%s: %w", schema.filename, err)
		}
		fmt.Fprintf(source, "\t%sSchemaVersion = %q\n", schema.typeName, version)
	}

	report := schemaDocument(schemas, "EvaluationReport")
	reportVersion, err := stringPropertyConst(report, "reportVersion")
	if err != nil {
		return fmt.Errorf("evaluation report: %w", err)
	}
	fmt.Fprintf(source, "\tReportVersion = %q\n", reportVersion)

	statusValues, err := stringEnumAt(
		report,
		"properties", "scenarios", "items", "properties", "status", "enum",
	)
	if err != nil {
		return fmt.Errorf("evaluation report statuses: %w", err)
	}
	for _, status := range statusValues {
		fmt.Fprintf(source, "\tReportScenarioStatus%s = %q\n", exportedName(status), status)
	}
	tokenResponse := schemaDocument(schemas, "DeviceTokenResponseContract")
	tokenStatuses, err := stringEnumAt(tokenResponse, "properties", "status", "enum")
	if err != nil {
		return fmt.Errorf("device token response statuses: %w", err)
	}
	for _, status := range tokenStatuses {
		fmt.Fprintf(source, "\tDeviceTokenStatus%s = %q\n", snakeToPascal(status), status)
	}
	slowDownStep, err := positiveIntegerAt(tokenResponse, "x-inside-slow-down-step-seconds")
	if err != nil {
		return fmt.Errorf("device token slow-down step: %w", err)
	}
	fmt.Fprintf(source, "\tDeviceTokenSlowDownStepSeconds int64 = %d\n", slowDownStep)
	durationMaximum, err := positiveIntegerAt(
		report,
		"properties", "scenarios", "items", "properties", "durationMilliseconds", "maximum",
	)
	if err != nil {
		return fmt.Errorf("evaluation report duration: %w", err)
	}
	fmt.Fprintf(
		source,
		"\tReportScenarioDurationMaximumMilliseconds int64 = %d\n",
		durationMaximum,
	)
	source.WriteString(")\n\n")

	diagnosticCodes, err := stringEnumAt(
		report,
		"properties", "scenarios", "items", "properties", "diagnostic", "properties", "code", "enum",
	)
	if err != nil {
		return fmt.Errorf("evaluation report diagnostics: %w", err)
	}
	diagnosticMessages, err := stringMapAt(report, "x-inside-diagnostic-messages")
	if err != nil {
		return fmt.Errorf("evaluation report diagnostic messages: %w", err)
	}
	if !sameStringSet(diagnosticCodes, sortedKeys(diagnosticMessages)) {
		return errors.New("evaluation report diagnostic codes and messages must have identical keys")
	}
	source.WriteString("const (\n")
	for _, code := range diagnosticCodes {
		fmt.Fprintf(source, "\tDiagnosticCode%s = %q\n", snakeToPascal(code), code)
	}
	source.WriteString(")\n\n")
	source.WriteString("var contractDiagnosticMessages = map[string]string{\n")
	for _, code := range sortedKeys(diagnosticMessages) {
		fmt.Fprintf(source, "\t%q: %q,\n", code, diagnosticMessages[code])
	}
	source.WriteString("}\n\n")

	caseSpec := schemaDocument(schemas, "CaseSpec")
	hosts, err := supportedHostPairs(caseSpec)
	if err != nil {
		return fmt.Errorf("case spec supported hosts: %w", err)
	}
	source.WriteString("var contractSupportedHosts = map[string]struct{}{\n")
	for _, host := range hosts {
		fmt.Fprintf(source, "\t%q: {},\n", host)
	}
	source.WriteString("}\n\n")
	return nil
}

func schemaDocument(schemas []loadedSchema, kind string) map[string]any {
	for _, schema := range schemas {
		if schema.kind == kind {
			return schema.document
		}
	}
	panic("generator schema registry is incomplete: " + kind)
}

func schemaID(document map[string]any) (string, error) {
	id, ok := document["$id"].(string)
	if !ok || id == "" {
		return "", errors.New("schema $id must be a non-empty string")
	}
	return id, nil
}

func stringPropertyConst(document map[string]any, property string) (string, error) {
	value, err := valueAt(document, "properties", property, "const")
	if err != nil {
		return "", err
	}
	text, ok := value.(string)
	if !ok || text == "" {
		return "", fmt.Errorf("property %s const must be a non-empty string", property)
	}
	return text, nil
}

func stringEnumAt(document map[string]any, path ...string) ([]string, error) {
	value, err := valueAt(document, path...)
	if err != nil {
		return nil, err
	}
	values, ok := value.([]any)
	if !ok || len(values) == 0 {
		return nil, errors.New("enum must be a non-empty array")
	}
	result := make([]string, 0, len(values))
	for _, candidate := range values {
		text, ok := candidate.(string)
		if !ok || text == "" {
			return nil, errors.New("enum values must be non-empty strings")
		}
		result = append(result, text)
	}
	return result, nil
}

func positiveIntegerAt(document map[string]any, path ...string) (int64, error) {
	value, err := valueAt(document, path...)
	if err != nil {
		return 0, err
	}
	number, ok := value.(float64)
	if !ok || number <= 0 || number != float64(int64(number)) {
		return 0, errors.New("value must be a positive integer")
	}
	return int64(number), nil
}

func stringMapAt(document map[string]any, path ...string) (map[string]string, error) {
	value, err := valueAt(document, path...)
	if err != nil {
		return nil, err
	}
	values, ok := value.(map[string]any)
	if !ok || len(values) == 0 {
		return nil, errors.New("value must be a non-empty object")
	}
	result := make(map[string]string, len(values))
	for name, candidate := range values {
		text, ok := candidate.(string)
		if !ok || text == "" {
			return nil, fmt.Errorf("value %q must be a non-empty string", name)
		}
		result[name] = text
	}
	return result, nil
}

func supportedHostPairs(document map[string]any) ([]string, error) {
	value, err := valueAt(document, "$defs", "supportedHost", "oneOf")
	if err != nil {
		return nil, err
	}
	variants, ok := value.([]any)
	if !ok || len(variants) == 0 {
		return nil, errors.New("supportedHost.oneOf must be a non-empty array")
	}
	hosts := make([]string, 0, len(variants))
	for _, variant := range variants {
		object, ok := variant.(map[string]any)
		if !ok {
			return nil, errors.New("supported host variant must be an object")
		}
		osName, err := stringPropertyConst(object, "os")
		if err != nil {
			return nil, err
		}
		architecture, err := stringPropertyConst(object, "arch")
		if err != nil {
			return nil, err
		}
		hosts = append(hosts, osName+"/"+architecture)
	}
	sort.Strings(hosts)
	return hosts, nil
}

func valueAt(document map[string]any, path ...string) (any, error) {
	var current any = document
	for _, segment := range path {
		object, ok := current.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("%s parent must be an object", strings.Join(path, "."))
		}
		value, exists := object[segment]
		if !exists {
			return nil, fmt.Errorf("missing %s", strings.Join(path, "."))
		}
		current = value
	}
	return current, nil
}

func sameStringSet(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	seen := make(map[string]struct{}, len(left))
	for _, value := range left {
		seen[value] = struct{}{}
	}
	for _, value := range right {
		if _, exists := seen[value]; !exists {
			return false
		}
	}
	return true
}

func snakeToPascal(value string) string {
	var result strings.Builder
	for _, part := range strings.Split(value, "_") {
		result.WriteString(exportedName(part))
	}
	return result.String()
}

func parseByteLimits(document map[string]any) (map[string]int64, error) {
	value, exists := document["x-inside-byte-limits"]
	if !exists {
		return nil, nil
	}
	rawLimits, ok := value.(map[string]any)
	if !ok {
		return nil, errors.New("x-inside-byte-limits must be an object")
	}
	limits := make(map[string]int64, len(rawLimits))
	for name, rawLimit := range rawLimits {
		limit, ok := rawLimit.(float64)
		if !ok || limit <= 0 || limit != float64(int64(limit)) {
			return nil, fmt.Errorf("byte limit %q must be a positive integer", name)
		}
		limits[name] = int64(limit)
	}
	return limits, nil
}

func inferStructs(
	document map[string]any,
	rootName string,
	documentsByID map[string]map[string]any,
) ([]goStruct, error) {
	generated := map[string]goStruct{}
	if _, err := inferGoType(document, document, rootName, generated, documentsByID); err != nil {
		return nil, err
	}
	names := sortedKeys(generated)
	result := make([]goStruct, 0, len(names))
	for _, name := range names {
		result = append(result, generated[name])
	}
	return result, nil
}

func inferGoType(
	schema map[string]any,
	root map[string]any,
	suggestedName string,
	generated map[string]goStruct,
	documentsByID map[string]map[string]any,
) (string, error) {
	if reference, ok := schema["$ref"].(string); ok {
		resolved, resolvedRoot, err := resolveReference(root, reference, documentsByID)
		if err != nil {
			return "", err
		}
		return inferGoType(resolved, resolvedRoot, suggestedName, generated, documentsByID)
	}
	if variants, ok := schema["oneOf"].([]any); ok && len(variants) > 0 {
		first, ok := variants[0].(map[string]any)
		if !ok {
			return "", errors.New("oneOf variant must be an object")
		}
		return inferGoType(first, root, suggestedName, generated, documentsByID)
	}

	schemaType, _ := schema["type"].(string)
	if schemaType == "" {
		schemaType = inferredPrimitiveType(schema)
	}
	switch schemaType {
	case "string":
		return "string", nil
	case "integer":
		return "int64", nil
	case "number":
		return "float64", nil
	case "boolean":
		return "bool", nil
	case "array":
		items, ok := schema["items"].(map[string]any)
		if !ok {
			return "", errors.New("array items must be a schema object")
		}
		itemType, err := inferGoType(
			items,
			root,
			suggestedName+"Item",
			generated,
			documentsByID,
		)
		if err != nil {
			return "", err
		}
		return "[]" + itemType, nil
	case "object":
		if _, exists := generated[suggestedName]; exists {
			return suggestedName, nil
		}
		generated[suggestedName] = goStruct{name: suggestedName}
		properties, ok := schema["properties"].(map[string]any)
		if !ok {
			return "", fmt.Errorf("object %s must declare properties", suggestedName)
		}
		required := stringSet(schema["required"])
		fields := make([]goField, 0, len(properties))
		for _, jsonName := range sortedKeys(properties) {
			property, ok := properties[jsonName].(map[string]any)
			if !ok {
				return "", fmt.Errorf("property %s.%s must be a schema object", suggestedName, jsonName)
			}
			fieldName := exportedName(jsonName)
			fieldType, err := inferGoType(
				property,
				root,
				suggestedName+fieldName,
				generated,
				documentsByID,
			)
			if err != nil {
				return "", fmt.Errorf("property %s.%s: %w", suggestedName, jsonName, err)
			}
			_, isRequired := required[jsonName]
			fields = append(fields, goField{
				name: fieldName, typeName: fieldType, jsonName: jsonName, optional: !isRequired,
			})
		}
		generated[suggestedName] = goStruct{name: suggestedName, fields: fields}
		return suggestedName, nil
	default:
		return "", fmt.Errorf("unsupported or missing schema type %q for %s", schemaType, suggestedName)
	}
}

func resolveReference(
	root map[string]any,
	reference string,
	documentsByID map[string]map[string]any,
) (map[string]any, map[string]any, error) {
	referenceRoot := root
	fragment := reference
	if !strings.HasPrefix(reference, "#") {
		parts := strings.SplitN(reference, "#", 2)
		if len(parts) != 2 {
			return nil, nil, fmt.Errorf("unsupported reference %q", reference)
		}
		var exists bool
		referenceRoot, exists = documentsByID[parts[0]]
		if !exists {
			return nil, nil, fmt.Errorf("reference resource %q is not registered", parts[0])
		}
		fragment = "#" + parts[1]
	}
	const prefix = "#/$defs/"
	if !strings.HasPrefix(fragment, prefix) {
		return nil, nil, fmt.Errorf("unsupported reference %q", reference)
	}
	definitions, ok := referenceRoot["$defs"].(map[string]any)
	if !ok {
		return nil, nil, errors.New("schema has no $defs")
	}
	resolved, ok := definitions[strings.TrimPrefix(fragment, prefix)].(map[string]any)
	if !ok {
		return nil, nil, fmt.Errorf("reference %q does not resolve to a schema object", reference)
	}
	return resolved, referenceRoot, nil
}

func inferredPrimitiveType(schema map[string]any) string {
	value, exists := schema["const"]
	if !exists {
		if values, ok := schema["enum"].([]any); ok && len(values) > 0 {
			value = values[0]
			exists = true
		}
	}
	if !exists {
		return ""
	}
	switch value.(type) {
	case string:
		return "string"
	case bool:
		return "boolean"
	case float64:
		return "number"
	default:
		return ""
	}
}

func stringSet(value any) map[string]struct{} {
	result := map[string]struct{}{}
	values, _ := value.([]any)
	for _, candidate := range values {
		if text, ok := candidate.(string); ok {
			result[text] = struct{}{}
		}
	}
	return result
}

func exportedName(value string) string {
	runes := []rune(value)
	if len(runes) == 0 {
		return "Field"
	}
	runes[0] = unicode.ToUpper(runes[0])
	result := string(runes)
	for _, replacement := range [][2]string{
		{"Sha256", "SHA256"},
		{"Sha", "SHA"},
		{"Url", "URL"},
		{"Id", "ID"},
		{"Os", "OS"},
	} {
		result = strings.ReplaceAll(result, replacement[0], replacement[1])
	}
	return result
}

func sortedKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
