FROM node:24-alpine

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @inside/backend build

EXPOSE 3001

CMD ["node", "apps/backend/dist/entrypoints/api.js"]
