import { randomUUID } from "node:crypto";
import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { signInFullStack } from "../support/full-stack-session";
test("owner assigns scoped course and the open cabinet converges through real BFF and PostgreSQL", async ({ page, context }, info) => {
  await signInFullStack(context, "OWNER");
  const owner = process.env.ENROLLMENT_OWNER_ID; if (!owner) throw new Error("Missing enrollment owner fixture");
  async function selectRecipient(surface: typeof page) {
    await surface.getByLabel("Подтверждённая Telegram identity получателя").fill("synthetic-owner-624");
    await surface.getByRole("button", { name: "Найти получателя", exact: true }).click();
    await expect(surface.getByText(`Аккаунт: ${String(owner)}`, { exact: true })).toBeVisible();
    await surface.getByRole("button", { name: "Выбрать получателя и показать назначения", exact: true }).click();
  }
  await page.goto("/authoring/billing");
  await expect(page.getByRole("heading", { name: "Оплата и права" })).toBeVisible();
  const tierName = `Практика ${info.project.name}`;
  await page.getByRole("button", { name: "Новый тариф", exact: true }).click();
  await page.getByLabel("Название", { exact: true }).first().fill(tierName);
  await page.getByLabel("Состав", { exact: true }).fill("materials\ncommunity=6");
  await page.getByLabel("Доступен для назначения").check();
  await page.getByLabel("Продукт: Инженерная практика", { exact: true }).check();
  await page.getByRole("button", { name: "Сохранить предложение", exact: true }).click();
  await expect(page.getByText("Предложение сохранено, редакция 1.", { exact: true })).toBeVisible();
  const rules = page.getByRole("heading", { name: "Ссылки активации курса и Tribute", exact: true }).locator("..");
  const code = randomUUID();
  await rules.getByLabel("Идентификатор нового правила").fill(randomUUID());
  await rules.getByLabel("Название правила").fill(`Правило ${info.project.name}`);
  await rules.getByLabel("Код активации").fill(code);
  await rules.getByRole("combobox", { name: "Тариф", exact: true }).selectOption({ label: tierName });
  await rules.getByLabel("Подтверждаемый источник").fill(`synthetic-course-${info.project.name}`);
  await rules.getByLabel("Начало по Москве").fill(new Date(Date.now() - 86_400_000).toISOString().slice(0, 16));
  await rules.getByLabel("Причина", { exact: true }).fill("Синтетическая публикация правила");
  await rules.getByLabel("Опубликовать правило").check();
  await rules.getByRole("button", { name: "Создать правило", exact: true }).evaluate(element => { element.scrollIntoView({ block: "center" }); });
  await rules.getByRole("button", { name: "Создать правило", exact: true }).click();
  await expect(rules.getByText(`Правило ${info.project.name} · Опубликовано`, { exact: true })).toBeVisible();
  const cabinet = await context.newPage(); await cabinet.goto("/account");
  async function openSubscription() {
    const navigation = cabinet.locator(`[data-account-section-nav="${info.project.name === "mobile-chromium" ? "mobile" : "desktop"}"]`);
    if (info.project.name === "mobile-chromium") {
      const toggle = navigation.getByRole("button", { name: /^Личный кабинет/u });
      if (await toggle.getAttribute("aria-expanded") !== "true") await toggle.click();
      await expect(toggle).toHaveAttribute("aria-expanded", "true");
    }
    await navigation.getByRole("link", { name: /^Подписка/u }).click();
  }
  await expect(cabinet.getByRole("dialog")).toBeVisible();
  await cabinet.keyboard.press("Escape");
  await expect(cabinet.getByRole("dialog")).not.toBeVisible();
  await page.getByLabel("Подтверждённая Telegram identity получателя").fill("absent-synthetic-624");
  await page.getByRole("button", { name: "Найти получателя", exact: true }).click();
  await expect(page.getByText("Подтверждённый аккаунт не найден. Проверьте точный идентификатор Telegram.")).toBeVisible();
  await selectRecipient(page);
  const otherOwner = await context.newPage(); await otherOwner.goto("/authoring/billing");
  await selectRecipient(otherOwner);
  await page.getByRole("heading", { name: "Назначить тариф", exact: true }).locator("..").getByRole("combobox", { name: "Тариф", exact: true }).selectOption({ label: `${tierName} · не продаётся` });
  await page.getByRole("combobox", { name: "Источник", exact: true }).first().selectOption("course");
  await page.getByLabel("Постоянный источник").fill(`synthetic-course-${info.project.name}`);
  await expect(page.getByLabel("Подтверждённая Telegram identity", { exact: true })).toHaveValue("synthetic-owner-624");
  await page.getByLabel("Причина и подтверждение").fill("Подтверждённый синтетический курс browser acceptance");
  await page.getByRole("button", { name: "Назначить без оплаты", exact: true }).evaluate(element => { element.scrollIntoView({ block: "center" }); });
  await page.getByRole("button", { name: "Назначить без оплаты", exact: true }).click();
  await expect(page.getByText("Тариф назначен. Платёж и расписание списаний не создавались.", { exact: true })).toBeVisible();
  await expect(otherOwner.getByRole("article").filter({ has: otherOwner.getByRole("heading", { name: tierName, exact: true }) })).toBeVisible();
  await openSubscription();
  await expect(cabinet).toHaveURL(/\/account\/subscription$/u);
  const card = cabinet.getByRole("article").filter({ has: cabinet.getByRole("heading", { name: tierName, exact: true }) });
  // Право без даты окончания не называет срок: кабинет его не показывает (Workspace #183).
  await expect(card.getByText("Срок", { exact: true })).toHaveCount(0);
  await expect(card.getByText("Следующего списания нет", { exact: true })).toBeVisible();
  const composition = card.locator("..");
  await composition.getByText("Посмотреть состав", { exact: true }).click();
  await expect(composition.getByRole("link", { name: "Инженерная практика" })).toHaveAttribute("href", "/guides/engineering-practice");
  await cabinet.screenshot({ path: info.outputPath("cabinet-enrollment.png"), fullPage: true });
  const changes = page.getByRole("heading", { name: `Изменить «${tierName}»` }).locator("..");
  await changes.getByRole("combobox", { name: "Действие" }).selectOption("revoke"); await changes.getByLabel("Причина", { exact: true }).fill("Синтетический отзыв"); await changes.getByRole("button", { name: "Применить изменение" }).click();
  await expect(card.getByText("Отозвано", { exact: true })).toBeVisible();
  const otherCard = otherOwner.getByRole("article").filter({ has: otherOwner.getByRole("heading", { name: tierName, exact: true }) });
  await expect(otherCard.getByText("Отозвано", { exact: true })).toBeVisible();
  await cabinet.goto("/account"); await openSubscription();
  await expect(card.getByText("Отозвано", { exact: true })).toBeVisible();
  await changes.getByRole("combobox", { name: "Действие" }).selectOption("restore"); await changes.getByLabel("Причина", { exact: true }).fill("Синтетическое восстановление"); await changes.getByRole("button", { name: "Применить изменение" }).click();
  await expect(card.getByText("Действует", { exact: true })).toBeVisible();
  // Unrelated catalog edits preserve finite benefit periods through real tiers.list and save.
  const catalogRow = page.getByText(`${tierName} · назначается`, { exact: true }).locator("..");
  await catalogRow.getByRole("button", { name: "Редактировать состав" }).click();
  await expect(page.getByLabel("Состав", { exact: true })).toHaveValue("community=6\nmaterials");
  await page.getByLabel("Название", { exact: true }).first().fill(`${tierName} обновлён`);
  await page.getByRole("button", { name: "Сохранить предложение", exact: true }).click();
  await expect(page.getByText("Предложение сохранено, редакция 2.", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Состав", { exact: true })).toHaveValue("community=6\nmaterials");
  // Add support explicitly, then selected expansion must update both open owner windows.
  await page.getByLabel("Состав", { exact: true }).fill("materials\ncommunity=6\nsupport");
  await page.getByRole("button", { name: "Сохранить предложение", exact: true }).click();
  await expect(page.getByText("Предложение сохранено, редакция 3.", { exact: true })).toBeVisible();
  const expansion = page.getByRole("heading", { name: "Расширить состав выбранных назначений" }).locator("..");
  await expansion.getByRole("combobox", { name: "Новая редакция тарифа", exact: true }).selectOption({ label: `${tierName} обновлён · редакция 3` });
  await expansion.getByLabel(`${tierName} · редакция 1 · course`, { exact: true }).check();
  await expansion.getByLabel("Причина расширения").fill("Синтетическая проверка двух окон");
  await expansion.getByRole("button", { name: "Проверить расширение", exact: true }).click();
  await expansion.getByRole("button", { name: "Применить проверенное расширение", exact: true }).click();
  await expect(otherOwner.getByRole("article").filter({ has: otherOwner.getByRole("heading", { name: `${tierName} обновлён`, exact: true }) })).toBeVisible();
  await expect(cabinet.getByRole("heading", { name: `${tierName} обновлён`, exact: true })).toBeVisible();
  await cabinet.screenshot({ path: info.outputPath("cabinet-enrollment.png"), fullPage: true });
  const savedRule = rules.getByText(`Правило ${info.project.name} · Опубликовано`, { exact: true }).locator("..");
  await savedRule.getByRole("combobox", { name: "Новая редакция тарифа", exact: true }).selectOption({ label: `${tierName} обновлён · редакция 3` });
  await savedRule.getByLabel("Причина обновления правила").fill("Явное обновление тарифа для прежней ссылки");
  await savedRule.getByRole("button", { name: "Обновить привязку тарифа", exact: true }).evaluate(element => { element.scrollIntoView({ block: "center" }); });
  await savedRule.getByRole("button", { name: "Обновить привязку тарифа", exact: true }).click();
  await expect(savedRule.getByText(/Закреплена редакция тарифа 3/u)).toBeVisible();
  await expect(savedRule.getByText(`Код: ${code} · источник: synthetic-course-${info.project.name} · Проверка курса`, { exact: true })).toBeVisible();
  await savedRule.scrollIntoViewIfNeeded();
  expect(await savedRule.evaluate(element => element.getBoundingClientRect().right <= window.innerWidth)).toBe(true);
  await savedRule.screenshot({ path: info.outputPath("activation-rule.png") });
  await otherOwner.close();
  const results = await new AxeBuilder({ page: cabinet }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(results.violations.filter(item => item.impact === "serious" || item.impact === "critical")).toEqual([]);
  expect(await cabinet.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const ownerAudit = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(ownerAudit.violations.filter(item => item.impact === "serious" || item.impact === "critical")).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const ownerSection = page.getByRole("heading", { name: "Тарифы и назначения", exact: true }).locator("..");
  expect(await ownerSection.evaluate(element => element.getBoundingClientRect().right <= window.innerWidth)).toBe(true);
  await ownerSection.screenshot({ path: info.outputPath("owner-enrollment.png") });
  await cabinet.close();
});
