import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { signInFullStack } from "../support/full-stack-session";
test("owner assigns scoped course and the open cabinet converges through real BFF and PostgreSQL", async ({ page, context }, info) => {
  await signInFullStack(context, "OWNER");
  const owner = process.env.ENROLLMENT_OWNER_ID; if (!owner) throw new Error("Missing enrollment owner fixture");
  await page.goto("/authoring/billing");
  await expect(page.getByRole("heading", { name: "Оплата и права" })).toBeVisible();
  const tierName = `Практика ${info.project.name}`;
  await page.getByRole("button", { name: "Новый тариф", exact: true }).click();
  await page.getByLabel("Название", { exact: true }).first().fill(tierName);
  await page.getByLabel("Состав", { exact: true }).fill("materials\ncommunity");
  await page.getByLabel("Доступен для назначения").check();
  await page.getByLabel("Гайд: Инженерная практика", { exact: true }).check();
  await page.getByRole("button", { name: "Сохранить предложение", exact: true }).click();
  await expect(page.getByText("Предложение сохранено, редакция 1.", { exact: true })).toBeVisible();
  const cabinet = await context.newPage(); await cabinet.goto("/account/subscription");
  await expect(cabinet.getByRole("dialog")).toBeVisible();
  await cabinet.keyboard.press("Escape");
  await expect(cabinet.getByRole("dialog")).not.toBeVisible();
  await page.getByLabel("Аккаунт получателя").fill(owner);
  await page.getByRole("heading", { name: "Назначить тариф", exact: true }).locator("..").getByRole("combobox", { name: "Тариф", exact: true }).selectOption({ label: `${tierName} · не продаётся` });
  await page.getByRole("combobox", { name: "Источник", exact: true }).first().selectOption("course");
  await page.getByLabel("Постоянный источник").fill(`synthetic-course-${info.project.name}`);
  await page.getByLabel("Подтверждённая Telegram identity").fill(`synthetic-${info.project.name}`);
  await page.getByLabel("Причина и подтверждение").fill("Подтверждённый синтетический курс browser acceptance");
  await page.getByRole("button", { name: "Назначить без оплаты", exact: true }).click();
  await expect(page.getByText("Тариф назначен. Платёж и расписание списаний не создавались.", { exact: true })).toBeVisible();
  const card = cabinet.getByRole("article").filter({ has: cabinet.getByRole("heading", { name: tierName, exact: true }) });
  await expect(card.getByText("Без даты окончания", { exact: true })).toBeVisible();
  await expect(card.getByText("Следующего списания нет", { exact: true })).toBeVisible();
  const composition = card.locator("..");
  await composition.getByText("Посмотреть состав", { exact: true }).click();
  await expect(composition.getByRole("link", { name: "Инженерная практика" })).toHaveAttribute("href", "/guides/engineering-practice");
  await cabinet.screenshot({ path: info.outputPath("cabinet-enrollment.png"), fullPage: true });
  const changes = page.getByRole("heading", { name: `Изменить «${tierName}»` }).locator("..");
  await changes.getByRole("combobox", { name: "Действие" }).selectOption("revoke"); await changes.getByLabel("Причина", { exact: true }).fill("Синтетический отзыв"); await changes.getByRole("button", { name: "Применить изменение" }).click();
  await expect(card.getByText("Отозвано", { exact: true })).toBeVisible();
  await changes.getByRole("combobox", { name: "Действие" }).selectOption("restore"); await changes.getByLabel("Причина", { exact: true }).fill("Синтетическое восстановление"); await changes.getByRole("button", { name: "Применить изменение" }).click();
  await expect(card.getByText("Действует", { exact: true })).toBeVisible();
  const results = await new AxeBuilder({ page: cabinet }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(results.violations.filter(item => item.impact === "serious" || item.impact === "critical")).toEqual([]);
  expect(await cabinet.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const ownerAudit = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(ownerAudit.violations.filter(item => item.impact === "serious" || item.impact === "critical")).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("heading", { name: "Тарифы и назначения", exact: true }).locator("..").screenshot({ path: info.outputPath("owner-enrollment.png") });
  await cabinet.close();
});
