export {
  MATERIAL_AUTHORING,
  type MaterialAuthoring,
  type CreateDraftError,
  type LoadDraftError,
  type PreviewRevisionError,
  type PublishRevisionError,
  type RestoreRevisionError,
  type ReviseDraftError,
  type UnpublishMaterialError,
  type ValidateRevisionError,
  type CreateDraftCommand,
  type CreateDraftResult,
  type MaterialRevisionMetadataChanges,
  type MaterialRevisionMetadataDto,
  type MaterialRevisionMetadataInput,
  type MaterialRevisionDto,
  type LoadDraftQuery,
  type LoadDraftResult,
  type PreviewRevisionDto,
  type PreviewRevisionResult,
  type PublicationLifecycleEventDto,
  type PublishRevisionCommand,
  type PublishRevisionResult,
  type ReviseDraftCommand,
  type ReviseDraftResult,
  type RestoreRevisionCommand,
  type RestoreRevisionResult,
  type SeriesMembershipInput,
  type ValidateRevisionQuery,
  type ValidateRevisionResult,
  type ValidatedRevisionDto,
  type UnpublishMaterialCommand,
  type UnpublishMaterialResult,
} from "./application/material-authoring.interface.js";
export type { AuthorPolicy } from "./application/ports/author-policy.js";
export {
  anonymousSubject,
  createBaselineContentAccess,
  type AccessDecision,
  type ContentAccess,
  type MaterialBodyResource,
  type Subject,
} from "./application/ports/content-access.js";
export {
  PUBLISHED_MATERIAL_READER,
  type PublishedMaterialReadDto,
  type PublishedMaterialReadError,
  type PublishedMaterialReadResult,
  type PublishedMaterialReader,
  type PublicMaterialProjectionDto,
} from "./application/published-material-reader.interface.js";
export type {
  MaterialBodyChange,
  JsonObject,
  JsonValue,
  MaterialBodyExtraction,
  MaterialBodyResourceSummary,
  MaterialBodySnapshot,
  RenderedBlock,
  RenderedMark,
  RenderedMaterialBody,
  RenderedText,
  ValidationIssue,
} from "./domain/material-body/material-body.js";
export { MaterialsModule } from "./materials.module.js";
export { createIdentityAuthorPolicy } from "./infrastructure/identity/identity-author-policy.js";
export { createMaterials, type Materials } from "./create-materials.js";
